server:
  port: 9000
  http2:
    enabled: true
  ssl:
    key-store: classpath:scs1671852680947_www.kudosama.cn_server.jks
    key-store-type: JKS
    key-store-password: Pe9*19GdoE31i#Hu
  tomcat:
    max-connections: 10000 # 一瞬间最大支持的并发连接数
    accept-count: 300 # 等待队列长度
    threads:
      max: 400 #最大工作线程 一般为核心数*200
      min-spare: 20 # 最小工作线程

#  address: 192.168.10.16

## 数据源配置
spring:
  mvc:
    path match:
      matching-strategy: ant_path_matcher
    async:
      request-timeout: 60000
  jackson:
    serialization:
      write-dates-as-timestamps: true
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 18789513633gtxy
    url: jdbc:mysql://localhost:3306/wmj_sms?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACY-HTML5
    encoding: UTF-8

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  #邮箱基本配置
  mail:
    #配置smtp服务主机地址
    host: smtp.qq.com
    #发送者邮箱
    username: null0x00@qq.com
    #配置密码,注意不是真正的密码，而是刚刚申请到的授权码
    password: pjclkhculuynbaeg
    #端口号465或587，SSL必须使用465
    port: 465
    #默认的邮件编码为UTF-8
    default-encoding: UTF-8
    #其他参数
    properties:
      mail:
        #配置SSL
        smtp:
          ssl:
            #放开ssl
            enable: true
            required: true
          #开启debug模式，这样邮件发送过程的日志会在控制台打印出来，方便排查错误
        debug: true
  main:
    allow-circular-references: true
  web:
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${file-upload-path}


## mybatis的配置
mybatis:
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: com.wmj.sms.mapper
  configuration:
    ## 下划线转驼峰
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      wmj:
        sms:
          mapper: debug

## 分页助手设置
page helper:
  helper-dialect: mysql

springfox:
  documentation:
    swagger-ui:
      enabled: true

file-upload-path: ./file


