server:
  port: 9000

## 数据源配置
spring:
  mvc:
    async:
      request-timeout: 60000
  jackson:
    serialization:
      write-dates-as-timestamps: true
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 18789513633gtxy
    url: jdbc:mysql://localhost:3306/team14_sms?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
    encoding: UTF-8

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${file-upload-path}


## mybatis的配置
mybatis:
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: com.team14.sms.mapper
  configuration:
    ## 下划线转驼峰
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      team14:
        sms:
          mapper: debug

## 分页助手设置
pagehelper:
  helper-dialect: mysql

#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
springfox:
  documentation:
    swagger-ui:
      enabled: true

file-upload-path: ./file

